[CTS-65] fix codestyle

diff --git a/githooks/pre-commit b/githooks/pre-commit
--- a/githooks/pre-commit
+++ b/githooks/pre-commit
@@ -1,6 +1,5 @@
 #!/usr/bin/env sh
-mypy .
-if [ $? -ne 0 ]
+if ! mypy .;
 then
     echo "Commit rejected. Fix mypy errors." >&2
     exit 1
@@ -9,9 +8,9 @@ fi
 SRC_FILE_LIST=$(git diff --cached --name-only --diff-filter=AMR | grep '.*\.py')
 if [ -n "$SRC_FILE_LIST" ]
 then
-    flake8 $SRC_FILE_LIST
-    if [ $? -ne 0 ]
+    if ! flake8 "$SRC_FILE_LIST";
     then
+        echo "Commit rejected. Fix flake8 errors." >&2
         exit 1
     fi
 fi
